# Generated by Django 4.1.5 on 2023-01-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('mL', 'Mililitre'), ('L', 'Litre'), ('tsp.', 'Teaspoon'), ('tbl.', 'Tablespoon'), ('fl oz', 'Fluid Ounce'), ('c', 'Cup'), ('p', 'Pint'), ('gal', 'Gallon'), ('mg', 'Miligram'), ('g', 'Gram'), ('kg', 'Kilogran'), ('lbs', 'Pounds'), ('oz', 'Ounce'), ('unit', 'Individual Unit')], max_length=5),
        ),
    ]
